{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pier-s3-gateway.secretName" . }}
  labels:
    {{- include "pier-s3-gateway.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ include "pier-s3-gateway.secretName" . }}
    creationPolicy: Owner
  data:
    {{- range $envKey, $property := .Values.externalSecret.properties }}
    - secretKey: {{ $envKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteKey }}
        property: {{ $property }}
    {{- end }}
{{- end }}
