{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pier-s3-gateway.fullname" . }}
  labels:
    {{- include "pier-s3-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.s3Host | quote }}
        - {{ .Values.ingress.uiHost | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.s3Host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pier-s3-gateway.fullname" . }}
                port:
                  number: {{ .Values.service.s3Port }}
    - host: {{ .Values.ingress.uiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pier-s3-gateway.fullname" . }}
                port:
                  number: {{ .Values.service.uiPort }}
{{- end }}
