apiVersion: v1
kind: Service
metadata:
  name: {{ include "pier-s3-gateway.fullname" . }}
  labels:
    {{- include "pier-s3-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pier-s3-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.service.s3Port }}
      targetPort: s3
      protocol: TCP
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: ui
      protocol: TCP
