apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pier-s3-gateway-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pier-s3-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: s3_access_key
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: s3_secret_key
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: keycloak_client_secret
    - secretKey: KEYCLOAK_URL
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: keycloak_url
    - secretKey: KEYCLOAK_REALM
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: keycloak_realm
    - secretKey: KEYCLOAK_CLIENT_ID
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: keycloak_client_id
    - secretKey: KEYCLOAK_JWKS_URL
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: keycloak_jwks_url
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: s3_endpoint
    - secretKey: S3_REGION
      remoteRef:
        key: secret/data/pier-s3-gateway
        property: s3_region
